apiVersion: apps/v1
kind: Deployment
metadata:
  name: scproject-deployment
spec:
  selector:
    matchLabels:
      app: sprs_api
  replicas: 2
  template:
    metadata:
      labels:
        app: sprs_api
    spec:
      containers:
        - name: sprsapi
          image: rismi/devopsimage1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084